//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarCodigoDeBarrasDePago", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GenerarCodigoDeBarrasDePagoResponse> GenerarCodigoDeBarrasDePagoAsync(ServiceReference1.GenerarCodigoDeBarrasDePagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarBoletaDePagoTasaDeJusticia", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaResponse> GenerarBoletaDePagoTasaDeJusticiaAsync(ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarCodigoDeBarrasDePagoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarCodigoDeBarrasDePago", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GenerarCodigoDeBarrasDePagoRequestBody Body;
        
        public GenerarCodigoDeBarrasDePagoRequest()
        {
        }
        
        public GenerarCodigoDeBarrasDePagoRequest(ServiceReference1.GenerarCodigoDeBarrasDePagoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarCodigoDeBarrasDePagoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal ImpuestoAbonar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NroDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Caratula;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal BaseImponible;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int idOrganismo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LetraReceptoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int NumeroReceptoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int SufijoReceptoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DetalleError;
        
        public GenerarCodigoDeBarrasDePagoRequestBody()
        {
        }
        
        public GenerarCodigoDeBarrasDePagoRequestBody(string Nombre, string Apellido, decimal ImpuestoAbonar, string TipoDocumento, string NroDocumento, string Caratula, decimal BaseImponible, int idOrganismo, string LetraReceptoria, int NumeroReceptoria, int SufijoReceptoria, string DetalleError)
        {
            this.Nombre = Nombre;
            this.Apellido = Apellido;
            this.ImpuestoAbonar = ImpuestoAbonar;
            this.TipoDocumento = TipoDocumento;
            this.NroDocumento = NroDocumento;
            this.Caratula = Caratula;
            this.BaseImponible = BaseImponible;
            this.idOrganismo = idOrganismo;
            this.LetraReceptoria = LetraReceptoria;
            this.NumeroReceptoria = NumeroReceptoria;
            this.SufijoReceptoria = SufijoReceptoria;
            this.DetalleError = DetalleError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarCodigoDeBarrasDePagoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarCodigoDeBarrasDePagoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GenerarCodigoDeBarrasDePagoResponseBody Body;
        
        public GenerarCodigoDeBarrasDePagoResponse()
        {
        }
        
        public GenerarCodigoDeBarrasDePagoResponse(ServiceReference1.GenerarCodigoDeBarrasDePagoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarCodigoDeBarrasDePagoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerarCodigoDeBarrasDePagoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DetalleError;
        
        public GenerarCodigoDeBarrasDePagoResponseBody()
        {
        }
        
        public GenerarCodigoDeBarrasDePagoResponseBody(string GenerarCodigoDeBarrasDePagoResult, string DetalleError)
        {
            this.GenerarCodigoDeBarrasDePagoResult = GenerarCodigoDeBarrasDePagoResult;
            this.DetalleError = DetalleError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarBoletaDePagoTasaDeJusticiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarBoletaDePagoTasaDeJusticia", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequestBody Body;
        
        public GenerarBoletaDePagoTasaDeJusticiaRequest()
        {
        }
        
        public GenerarBoletaDePagoTasaDeJusticiaRequest(ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarBoletaDePagoTasaDeJusticiaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal ImpuestoAbonar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NroDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Caratula;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal BaseImponible;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int idOrganismo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string LetraReceptoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int NumeroReceptoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int SufijoReceptoria;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CodigoBarras;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DetalleError;
        
        public GenerarBoletaDePagoTasaDeJusticiaRequestBody()
        {
        }
        
        public GenerarBoletaDePagoTasaDeJusticiaRequestBody(string Nombre, string Apellido, decimal ImpuestoAbonar, string TipoDocumento, string NroDocumento, string Caratula, decimal BaseImponible, int idOrganismo, string LetraReceptoria, int NumeroReceptoria, int SufijoReceptoria, string CodigoBarras, string DetalleError)
        {
            this.Nombre = Nombre;
            this.Apellido = Apellido;
            this.ImpuestoAbonar = ImpuestoAbonar;
            this.TipoDocumento = TipoDocumento;
            this.NroDocumento = NroDocumento;
            this.Caratula = Caratula;
            this.BaseImponible = BaseImponible;
            this.idOrganismo = idOrganismo;
            this.LetraReceptoria = LetraReceptoria;
            this.NumeroReceptoria = NumeroReceptoria;
            this.SufijoReceptoria = SufijoReceptoria;
            this.CodigoBarras = CodigoBarras;
            this.DetalleError = DetalleError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarBoletaDePagoTasaDeJusticiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarBoletaDePagoTasaDeJusticiaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaResponseBody Body;
        
        public GenerarBoletaDePagoTasaDeJusticiaResponse()
        {
        }
        
        public GenerarBoletaDePagoTasaDeJusticiaResponse(ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarBoletaDePagoTasaDeJusticiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GenerarBoletaDePagoTasaDeJusticiaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodigoBarras;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DetalleError;
        
        public GenerarBoletaDePagoTasaDeJusticiaResponseBody()
        {
        }
        
        public GenerarBoletaDePagoTasaDeJusticiaResponseBody(byte[] GenerarBoletaDePagoTasaDeJusticiaResult, string CodigoBarras, string DetalleError)
        {
            this.GenerarBoletaDePagoTasaDeJusticiaResult = GenerarBoletaDePagoTasaDeJusticiaResult;
            this.CodigoBarras = CodigoBarras;
            this.DetalleError = DetalleError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface ServiceSoapChannel : ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.ServiceSoap>, ServiceReference1.ServiceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GenerarCodigoDeBarrasDePagoResponse> ServiceReference1.ServiceSoap.GenerarCodigoDeBarrasDePagoAsync(ServiceReference1.GenerarCodigoDeBarrasDePagoRequest request)
        {
            return base.Channel.GenerarCodigoDeBarrasDePagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GenerarCodigoDeBarrasDePagoResponse> GenerarCodigoDeBarrasDePagoAsync(string Nombre, string Apellido, decimal ImpuestoAbonar, string TipoDocumento, string NroDocumento, string Caratula, decimal BaseImponible, int idOrganismo, string LetraReceptoria, int NumeroReceptoria, int SufijoReceptoria, string DetalleError)
        {
            ServiceReference1.GenerarCodigoDeBarrasDePagoRequest inValue = new ServiceReference1.GenerarCodigoDeBarrasDePagoRequest();
            inValue.Body = new ServiceReference1.GenerarCodigoDeBarrasDePagoRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Apellido = Apellido;
            inValue.Body.ImpuestoAbonar = ImpuestoAbonar;
            inValue.Body.TipoDocumento = TipoDocumento;
            inValue.Body.NroDocumento = NroDocumento;
            inValue.Body.Caratula = Caratula;
            inValue.Body.BaseImponible = BaseImponible;
            inValue.Body.idOrganismo = idOrganismo;
            inValue.Body.LetraReceptoria = LetraReceptoria;
            inValue.Body.NumeroReceptoria = NumeroReceptoria;
            inValue.Body.SufijoReceptoria = SufijoReceptoria;
            inValue.Body.DetalleError = DetalleError;
            return ((ServiceReference1.ServiceSoap)(this)).GenerarCodigoDeBarrasDePagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaResponse> ServiceReference1.ServiceSoap.GenerarBoletaDePagoTasaDeJusticiaAsync(ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequest request)
        {
            return base.Channel.GenerarBoletaDePagoTasaDeJusticiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaResponse> GenerarBoletaDePagoTasaDeJusticiaAsync(string Nombre, string Apellido, decimal ImpuestoAbonar, string TipoDocumento, string NroDocumento, string Caratula, decimal BaseImponible, int idOrganismo, string LetraReceptoria, int NumeroReceptoria, int SufijoReceptoria, string CodigoBarras, string DetalleError)
        {
            ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequest inValue = new ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequest();
            inValue.Body = new ServiceReference1.GenerarBoletaDePagoTasaDeJusticiaRequestBody();
            inValue.Body.Nombre = Nombre;
            inValue.Body.Apellido = Apellido;
            inValue.Body.ImpuestoAbonar = ImpuestoAbonar;
            inValue.Body.TipoDocumento = TipoDocumento;
            inValue.Body.NroDocumento = NroDocumento;
            inValue.Body.Caratula = Caratula;
            inValue.Body.BaseImponible = BaseImponible;
            inValue.Body.idOrganismo = idOrganismo;
            inValue.Body.LetraReceptoria = LetraReceptoria;
            inValue.Body.NumeroReceptoria = NumeroReceptoria;
            inValue.Body.SufijoReceptoria = SufijoReceptoria;
            inValue.Body.CodigoBarras = CodigoBarras;
            inValue.Body.DetalleError = DetalleError;
            return ((ServiceReference1.ServiceSoap)(this)).GenerarBoletaDePagoTasaDeJusticiaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://tasatesting.scba.gov.ar/ws/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://tasatesting.scba.gov.ar/ws/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
